# Generated by Django 4.2 on 2025-03-06 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='hotel_room_image/'),
            preserve_default=False,
        ),
    ]
