# Generated by Django 4.2 on 2025-03-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_uid',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
