# Generated by Django 4.2 on 2025-03-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterSubscriber',
            new_name='News',
        ),
    ]
