# Generated by Django 4.2 on 2025-03-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_guest_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_nights',
        ),
    ]
