# Generated by Django 4.2 on 2025-04-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_remove_booking_total_nights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.roomtype'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Number of people the room can accommodate'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price, if applicable', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(default='default_room.jpg', upload_to='hotel_room_image/'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, help_text='Standard price per night', max_digits=10),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='service',
            field=models.CharField(help_text='E.g., WiFi, TV, AC, Breakfast', max_length=100),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='size',
            field=models.PositiveIntegerField(default=1, help_text='Size in square meters'),
        ),
    ]
